services:
- type: web
  name: asset-reserve-dashboard
  runtime: python
  envVars:
  - key: ASSET_DB_PATH
    value: asset_reserve_metrics.sqlite
  - key: BIRDEYE_API_KEY
    sync: false
  - key: HELIUS_API_KEY
    sync: false
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  autoDeploy: true

- type: cron
  name: asset-reserve-snapshot
  runtime: python
  schedule: "*/30 * * * *" # every 30 minutes
  envVars:
  - key: ASSET_DB_PATH
    value: asset_reserve_metrics.sqlite
  - key: BIRDEYE_API_KEY
    sync: false
  - key: HELIUS_API_KEY
    sync: false
  buildCommand: pip install -r requirements.txt
  startCommand: python scripts/snapshot.py

